---
- name: config_apt_cacher | configuring apt caching (Client)
  template:
    src: etc/apt/apt.conf.d/02aptcacherng.j2
    dest: /etc/apt/apt.conf.d/02aptcacherng
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: _apt_caching_configured
  when: >
        enable_apt_caching | bool

- name: debian_client | removing apt caching (Client)
  file:
    path: "{{ item }}"
    state: absent
  register: _apt_caching_configured
  with_items:
    # configured when node is deployed using PXE/TFTP and proxy is defined
    - '/etc/apt/apt.conf'
    - '/etc/apt/apt.conf.d/02aptcacherng'
  when: >
        not (enable_apt_caching | bool)

- name: config_apt_cacher | refreshing apt from cache server (Client)
  apt:
    update_cache: yes
  when: _apt_caching_configured['changed']
